spring:
  application:
    name: iam-service
  data:
    redis:
      host: ${ARCHIPIO_IAM_SERVICE_CACHE_HOST}
      port: ${ARCHIPIO_IAM_SERVICE_CACHE_PORT}
      password: ${ARCHIPIO_IAM_SERVICE_CACHE_PASSWORD}
server:
  port: 18081
jwt:
  secret: ${ARCHIPIO_IAM_SERVICE_SECRET}
  access-token:
    ttl: 1200
  refresh-token:
    ttl: 604800
rest:
  clients:
    user-service:
      url: ${ARCHIPIO_IAM_SERVICE_USER_SERVICE_URL}
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs