spring:
  application:
    name: iam-service
  data:
    redis:
      database: 0
      host: localhost
      port: 16379
      password: password
server:
  port: 18081
jwt:
  secret: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
  access-token:
    ttl: 1200
  refresh-token:
    ttl: 604800
